# Generated by Django 3.2.8 on 2021-10-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.DeleteModel(
            name='Postm',
        ),
    ]
