# Generated by Django 3.2.8 on 2021-10-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_post_imagep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
