# Generated by Django 3.2.8 on 2021-10-19 13:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_auto_20211019_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagep',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
